# Docker Compose configuration for Oracle1 AgenticDosNode
# ARM64 optimized version with proper dependency management

networks:
  agentic_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
  tailscale_net:
    external: true
    name: tailscale

volumes:
  n8n_data:
  redis_data:
  postgres_data:
  prometheus_data:
  grafana_data:
  qdrant_replica:
  kong_data:

services:
  # PostgreSQL Database (ARM64 compatible)
  postgres:
    image: postgres:16-alpine
    platform: linux/arm64
    container_name: oracle1-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-agentic}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_DB=${POSTGRES_DB:-agentic_db}
      - POSTGRES_MULTIPLE_DATABASES=n8n,langgraph,kong
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - agentic_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-agentic}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # Redis Cache & Queue (ARM64 compatible)
  redis:
    image: redis:7-alpine
    platform: linux/arm64
    container_name: oracle1-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-changeme}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - agentic_net
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD:-changeme}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # n8n Automation Platform (ARM64 compatible)
  n8n:
    image: n8nio/n8n:latest
    platform: linux/arm64
    container_name: oracle1-n8n
    environment:
      - N8N_HOST=${NODE_IP:-100.96.197.84}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://${NODE_IP:-100.96.197.84}:5678/
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-changeme}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=${POSTGRES_USER:-agentic}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-n8nadmin123!}
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"
    networks:
      - agentic_net
      - tailscale_net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # Kong API Gateway (ARM64 compatible)
  kong:
    image: kong:latest
    platform: linux/arm64
    container_name: oracle1-kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_PORT=5432
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=${POSTGRES_USER:-agentic}
      - KONG_PG_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
      - KONG_PLUGINS=bundled
      - KONG_NGINX_WORKER_PROCESSES=2
    volumes:
      - kong_data:/usr/local/kong
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
    networks:
      - agentic_net
      - tailscale_net
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # Qdrant Vector Database Replica (ARM64 compatible)
  qdrant-replica:
    image: qdrant/qdrant:latest
    platform: linux/arm64
    container_name: oracle1-qdrant
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage
      - QDRANT__TELEMETRY_DISABLED=true
    volumes:
      - qdrant_replica:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - agentic_net
      - tailscale_net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Prometheus Monitoring (ARM64 compatible)
  prometheus:
    image: prom/prometheus:latest
    platform: linux/arm64
    container_name: oracle1-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    ports:
      - "9090:9090"
    networks:
      - agentic_net
      - tailscale_net
    restart: unless-stopped

  # Grafana Dashboard (ARM64 compatible)
  grafana:
    image: grafana/grafana:latest
    platform: linux/arm64
    container_name: oracle1-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-changeme}
      - GF_INSTALL_PLUGINS=redis-datasource,grafana-postgresql-datasource
      - GF_SERVER_ROOT_URL=http://${NODE_IP:-100.96.197.84}:3000
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - agentic_net
    depends_on:
      prometheus:
        condition: service_started
    restart: unless-stopped

  # Node Exporter for system metrics (ARM64 compatible)
  node-exporter:
    image: prom/node-exporter:latest
    platform: linux/arm64
    container_name: oracle1-node-exporter
    ports:
      - "9100:9100"
    networks:
      - agentic_net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped

  # Process Exporter for detailed process monitoring (ARM64 compatible)
  process-exporter:
    image: ncabatoff/process-exporter:latest
    platform: linux/arm64
    container_name: oracle1-process-exporter
    ports:
      - "9256:9256"
    networks:
      - agentic_net
    volumes:
      - /proc:/host/proc:ro
      - ./process-exporter:/config:ro
    command:
      - '--procfs=/host/proc'
      - '--config.path=/config/process-exporter.yml'
    restart: unless-stopped

  # cAdvisor for container metrics (ARM64 compatible)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    platform: linux/arm64
    container_name: oracle1-cadvisor
    ports:
      - "8082:8080"
    networks:
      - agentic_net
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    restart: unless-stopped

  # Tailscale Sidecar (ARM64 compatible)
  tailscale:
    image: tailscale/tailscale:latest
    platform: linux/arm64
    container_name: oracle1-tailscale
    hostname: oracle1
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ROUTES=172.21.0.0/24
    volumes:
      - ./tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      - tailscale_net
      - agentic_net
    restart: unless-stopped